### PR TITLE
Issue#17

### PR DESCRIPTION
**Pull request by tinvaan**
This request deals with the fix for ISSUE#17 only .

### CODE REVIEW

**Comment by swiftarrow** [comment]
Awesome!  I'll check it out soon.

**Comment by swiftarrow** [comment]
Hey Harish, 

Sorry I couldn't get to this earlier!  Thanks for the pull request.

Unfortunately, when I checkout your branch and try to run it, I get a syntax error.  See the screendump here:
http://awesomescreenshot.com/0f523t1sf3  (screenshot will be taken down after a month)

I started from a clean slate (cloned the master trunk, checked out your branch, pulled it in, and then ran syncdb, then tried to test) just to be sure.

Thanks in advance for fixing that!

**Comment by tinvaan** [comment]
Well , that's precisely what I'm getting aswell . It turns out that my 'master' branch works fine , but the all the others show some syntax error . I don't know how , will try to fix it asap .

Thanks

**Comment by varrunr** [comment]
It would be good to include test steps and results in future commits/merge requests.

**Comment by swiftarrow** [comment]
Thanks Varrun for teaching us all GitHub etiquette!!!  :+1:

**Comment by varrunr** [comment]
Its more of software development etiquette than GitHub etiquette :-)

**Comment by tinvaan** [comment]
I'm sorry for the mess . Anyways , I've updated my pull request in accordance to what @varrunr had mentioned . However , I still can't create a Road Assessment entry on my system . 
Can @swiftarrow  or @varrunr  please verify if it's working ??

**Comment by varrunr** [comment]
It seems to work fine for me. @swiftarrow , can you verify?

@harishnavnit , in future please follow the process for contribution 
1. Commit only working changes, i.e each commit should not have broken code. You should test out the code before committing to the repo.
2. Always do a git pull before pushing.
3. Include detailed steps on the testing you did for the pull request. If your testing indicates a problem, do not commit or submit a pull request until your resolve the issues, instead send over a patch with your changes and description of the problems you are facing. 

Sorry to be such a stickler for these processes, but its what keeps the repository clean and maintainable in the end.

**Comment by swiftarrow** [comment]
Seems to work properly.  Road Assessment create and delete works.
Congrats, @harishnavnit!!!  

@varrunr if there's nothing else, can I ask you to merge this?  Thanks!

**Comment by tinvaan** [comment]
That's great :) :+1:

**Comment by varrunr** [comment]
@harishnavnit , congrats on your first successful merge! :-)

**Pull request merged**
